### PR TITLE
fix(unity-bootstrap-theme): adjust endorsed-logo css

### PR DESCRIPTION
**Pull request by scott-williams-az**
combine media queries and use css3 variable to implement

### Links

- [component-footer](https://unity.web.asu.edu/@asu/component-footer/index.html?path=/story/uds-asu-footer--unit-logo)
- [unity-bootstrap-theme](https://unity.web.asu.edu/@asu/unity-bootstrap-theme/index.html?path=/story/organisms-global-footer-examples--zero-columns-example&args=header:false)
- [JIRA ticket](https://asudev.jira.com/browse/UDS-1455)

### Checklist

- [x] Unity project successfully builds from root `yarn install` & `yarn build`
- [x] Commits do not contain multiple scopes
~- [ ] Add/updated examples~
~- [ ] Add/updated READMEs/docs~
~- [ ] No new console errors~
~- [ ] Accessibility checks~

### Browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### CODE REVIEW

**Comment by scott-williams-az** [comment]
@davidornelas11 @mlsamuelson  What do you think of this css3 variable pattern. I think it can help in a lot of ways, but if we do not have a clear pattern it may end up confusing us. So I am open to ideas. @media query changes the var values and does not add any new rules. 

WS2 or other platforms can then use the variable if needed, and will not have to use `!important`

So in this PR code, css variables are at the root style and I am trying to be specific about how the variables are named
```
#endorsed-logo {
  --endorsed-logo-display: block; // is meant for endorsed-logo attribute display
  --endorsed-logo-img-width: // is meant for endorsed-logo  img attribute width
```

Can you think of a other things we should lookout for or think about. We don't want css variable to start conflicting.

**Comment by mlsamuelson** [comment]
@scott-williams-az This pattern makes sense to me. I wonder about how best to surface this (or at least the functionality it enables) to consumers. Perhaps simply socializing it when possible. AND of course it would be a candidate for being a documented pattern under the https://asudev.jira.com/browse/UDS-1586 effort.

The naming convention is clear, though what do you think about avoiding using `-y` and instead being more explicit and granular with `-top` and `-bottom` in an attempt to align more closely with the naming convention of `selector-property`? Might make it more of a no-brainer what to name the variables.

I would like to get @bebaps 's opinion on it as well, as he's a good representative power-user of the theme.

**Comment by bebaps** [comment]
@mlsamuelson @scott-williams-az I do agree with this approach and the use of CSS Variables in general, where it makes sense. I don't have all the context here, but I am guessing that the core discussion is around the naming pattern and not the use of the variables themselves. On that front, I do like this pattern, and I also agree that we should not use the shorthand `-y` but use `top|bottom|left|right`. If this PR will essentially set the precedent for the use of the variables and its naming, then I agree with this.

**Review by bebaps — DISMISSED** [review]
@mlsamuelson @scott-williams-az I do agree with this approach and the use of CSS Variables in general, where it makes sense. I don't have all the context here, but I am guessing that the core discussion is around the naming pattern and not the use of the variables themselves. On that front, I do like this pattern, and I also agree that we should not use the shorthand `-y` but use `top|bottom|left|right`. If this PR will essentially set the precedent for the use of the variables and its naming, then I agree with this.

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
Thanks, @bebaps . Your review was in the spirit I was hoping for.

@scott-williams-az Can you change the use of `-y` as noted in previous comments. After that, this looks good to go.

**Review by mlsamuelson — APPROVED** [review]

**Pull request merged**
