### PR TITLE
fix(unity-bootstrap-theme): update styles for heroes component

### PR DESCRIPTION
**Pull request by maycomayco**
### Description

Update heroes component styles and stories to match with the last changes from bootstrap4-theme. I used cherry-pick concept in order to get the original changes from bootstrap4-theme package

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1306)
- [Unity Design Kit](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/)

### Checklist

- [x] Unity project successfully builds from root `yarn install` & `yarn build`
- [x] Commits do not contain multiple scopes

### Browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

### CODE REVIEW

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
@maycomayco Merge conflicts to resolve on this PR.

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
@maycomayco I'm seeing changes in the `packages-disabled/bootstrap4-theme` folder with this PR... is it regressing the changes in the disabled package? Even though it's disabled, we should keep it in its final state.

**Review by mlsamuelson — COMMENTED** [review]
PR looks good and builds fine, otherwise.

**Comment by maycomayco** [comment]
> @maycomayco I'm seeing changes in the `packages-disabled/bootstrap4-theme` folder with this PR... is it regressing the changes in the disabled package? Even though it's disabled, we should keep it in its final state.

This is because I updated the latest changes for `bootstrap4-theme` here. However, I shouldn't have done it

**Review by mlsamuelson — APPROVED** [review]

**Pull request merged**
