### PR TITLE
UDS-1756: feat(unity-bootstrap-theme): modified _banner.scss, banners.templates.stories.js for accessibility

### PR DESCRIPTION
**Pull request by juanmitriatti**
feat(unity-bootstrap-theme): modified _banner.scss, banners.templates.stories.js for accessibility

UDS-1756

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1756)
- [Unity reference site](https://asu.github.io/asu-unity-stack/)
- [Unity Design Kit](https://shared-assets.adobe.com/link/fb14b288-bf63-47e0-5d30-384de5560455)

### FOR APPROVERS

- [Percy build approval](https://percy.io/5eae92d9/-all-UDS-packages)

### CODE REVIEW

**Comment by scott-williams-az** [comment]
@mlsamuelson  I am concerned with changing the banner to H1. Banner is already wrapped in a section which is good. We want to make sure the page structure (with different section, article, aside, etc) is correct to allow 2 H1's.

I found this, however the detail in this section still left me with questions.
https://www.w3.org/WAI/tutorials/page-structure/headings/#main-heading-after-navigation

**Comment by juanmitriatti** [comment]
> @mlsamuelson I am concerned with changing the banner to H1. Banner is already wrapped in a section which is good. We want to make sure the page structure (with different section, article, aside, etc) is correct to allow 2 H1's.
> 
> I found this, however the detail in this section still left me with questions. https://www.w3.org/WAI/tutorials/page-structure/headings/#main-heading-after-navigation

Hi @scott-williams-az  , @mlsamuelson 
The reason for changing the banner to an H1 is to meet an accessibility requirement mentioned in this ticket: https://asudev.jira.com/browse/WS2-2194.

Thanks!

**Comment by mlsamuelson** [comment]
Let's confirm with Kathy.

**Comment by mlsamuelson** [comment]
We need to hold on this until we have clarity from Kathy. See the conversation at https://asu-tech.slack.com/archives/CT01Z74KY/p1722018704187699

**Review by mlsamuelson — APPROVED** [review]
Per Kathy's updated rationale for the request on https://asudev.jira.com/browse/WS2-2221 (item number 4), I'm okay with this going in, if @scott-williams-az 's concerns are adequately resolved by that, as well.

@scott-williams-az If you approve, this can be merged.

**Comment by scott-williams-az** [comment]
Looks good

**Pull request merged**
