### PR TITLE
WS2-1634: fix(app-degree-pages): add check to the anchorMenu for false values

### PR DESCRIPTION
**Pull request by bebaps**
### Description

Currently, the Anchor Menu on the degree pages renders by default with no items. In this state, there is a bug where if you scroll down the page, then scroll back up the page, the menu will then disappear completely.

This PR adds a check to the `OnThisPageAnchorMenu` component to see if all values from the `anchorMenu` prop are false. If true, the component returns `null`.

This really may not be the best place to put this logic, or returning null for a component might just be a terrible idea. The end goal is to prevent the component from rendering at all if all the initial `anchorMenu` values are false. Please suggest changes as needed.

### Links

- [Unity reference site](https://unity.web.asu.edu/)
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1634)

### Checklist

- [x] Unity project successfully builds from root `yarn install` & `yarn build`
- [x] Commits do not contain multiple scopes
- [x] No new console errors

### Browsers

- [x] Chrome
- [x] Safari
- [x] Firefox

### CODE REVIEW

**Review by scott-williams-az — COMMENTED** [review]
Nice job, it's always good to check values before rendering, I noticed we are also filtering out the false values below line 38,

React has a shortcut which will check a condition before rendering...

the format looks like this 
`return (condition && <Component/>)`

in order to keep the filter logic in one place can we update to the following?

```
return (
    anchorList.length > 0 && (
      <AnchorMenu
        items={anchorList}
        firstElementId={anchorList[0]?.targetIdName}
        focusFirstFocusableElement={false}
      />
    )
  );
```

**Review by scott-williams-az — CHANGES_REQUESTED** [review]
previous comment

**Review by scott-williams-az — CHANGES_REQUESTED** [review]
This logic might be better in components-core https://github.com/ASU/asu-unity-stack/blob/dev/packages/components-core/src/components/AnchorMenu/index.js#L183
```
  return (
    items?.length > 0 && (
      <AnchorMenuWrapper...
      </AnchorMenuWrapper>
    )
  );
```

**Comment by bebaps** [comment]
Comment to myself so I don't forget, update this PR as follows:

- implement Scott's most recent suggestion
- remove my code
- verify all working as expected

**Comment by bebaps** [comment]
@scott-williams-az requested changes made, verified they work as expected.

**Review by scott-williams-az — APPROVED** [review]
LGTM

**Review by mlsamuelson — APPROVED** [review]

**Pull request merged**
