### PR TITLE
docs(unity-bootstrap-theme): add UPGRADE.md

### PR DESCRIPTION
**Pull request by mlsamuelson**
### Description

We need to add an UPGRADE.md file for the Bootstrap 4 to Bootstrap 5 migration.

### Links

- [JIRA ticket - UDS-1322](https://asudev.jira.com/browse/UDS-1322)

### Checklist

- [x] Commits do not contain multiple scopes

### CODE REVIEW

**Comment by scott-williams-az** [comment]
At this time, this looks complete.

**Comment by scott-williams-az** [comment]
I did not see any mention of design tokens, but I do not think that is necessary. I am mentioning it just in case.

**Comment by mlsamuelson** [comment]
@scott-williams-az Thanks for reviewing. For the purpose of this document, I don't think we need make note of the design tokens.  I'll leave this in draft until we finalize by replacing the `TODO` items.

Thanks!

**Review by maycomayco — COMMENTED** [review]
I think this document is pretty good We only have to finish the TODOs

**Pull request merged**
