### PR TITLE
refactor(unity-bootstrap-theme): migration of Bootstrap's helpers and utilities

### PR DESCRIPTION
**Pull request by maycomayco**
### Description

Migration of bootstrap helpers and utilities
This has a dependency on https://github.com/ASU/asu-unity-stack/pull/1002

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1318)

### Checklist

- [x] Unity project successfully builds from root `yarn install` & `yarn build`
- [x] Commits do not contain multiple scopes
- [ ] Add/updated examples
- [ ] No new console errors
- [ ] Accessibility checks

### Browsers

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### CODE REVIEW

**Review by scott-williams-az — APPROVED** [review]
definitely this is something to remember to include with an upgrade guide for our users
LGTM

**Review by mlsamuelson — APPROVED** [review]
Good stuff. I added a link to UDS-1318 from the ticket to document the migration details: https://asudev.jira.com/browse/UDS-1322

**Comment by mlsamuelson** [comment]
Throws linting errors that will need to be cleaned up prior to the `migration-to-bs5` branch being merged. Those can be cleaned up here before merge - or you can merge and clean up there. I'll leave it to your preference, @maycomayco

**Review by davidornelas11 — APPROVED** [review]
LGTM

**Pull request merged**
