### PR TITLE
fix(app-webdir-ui): focus cursor in search box on page load

### PR DESCRIPTION
**Pull request by davidornelas11**
### Description
Focus cursor in search bar on page load

### Links

- [Unity reference site](https://unity.web.asu.edu/@asu/app-webdir-ui/index.html?path=/story/organisms-search-page-templates--search-page-example)
- [JIRA ticket](https://asudev.jira.com/browse/SCHWEB-1089?atlOrigin=eyJpIjoiNDkxOGNiYmZkMTgzNGQ4NWFkNTc0NjM4Mzk2YTExYTIiLCJwIjoiaiJ9)

### Checklist

- [x] Unity project successfully builds from root `yarn install` & `yarn build`
- [x] Commits do not contain multiple scopes
- [x] Add/updated examples
- [x] Add/updated READMEs/docs
- [x] No new console errors
- [x] Accessibility checks

### Browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

### CODE REVIEW

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
Throws error in Storybook:
`(0 , react__WEBPACK_IMPORTED_MODULE_13__.ref) is not a function
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_13__.ref) is not a function`

Errors go away and the story renders if you import `useRef` instead of `ref` on line 3 and replace `ref` with `useRef` on line 36.

The focus doesn't correctly update, though. Because it looks like you're missing `ref={inputRef}` on the input tag, around line 131.

**Review by mlsamuelson — COMMENTED** [review]
Updates look good, but see https://github.com/ASU/asu-unity-stack/pull/1177 which addresses the Storybook error "Rendered more hooks than during the previous render."

**Comment by mlsamuelson** [comment]
The #1177 PR issue turns out to be unrelated to this PR. Just for the record.

**Review by mlsamuelson — DISMISSED** [review]

**Comment by scott-williams-az** [comment]
Do we need a way enable/disable focus onLoad? Have we identified the expected behavoir when there are 2 elements trying to focus on page load?
See Tabbed Panel https://github.com/ASU/asu-unity-stack/blob/dev/packages/components-core/src/components/TabbedPanels/components/TabHeader.js#L22

**Comment by mlsamuelson** [comment]
@scott-williams-az Good point. I didn't realize that the tabbed panels were also capturing focus. And in the case of the Search Page component, it's using tabbed panels and the search focus...

**Comment by scott-williams-az** [comment]
Now that I think about it, I may have changed the tabbed panels from `focus` to `scroll into view` (the code to `focus` on the tab might actually be unused, if it is we can remove it)

**Comment by scott-williams-az** [comment]
Sorry for the back and forth, we are setting focus on the tabbed panels
https://github.com/ASU/asu-unity-stack/blob/dev/packages/components-core/src/components/TabbedPanels/index.js#L62

**Comment by mlsamuelson** [comment]
I think that ought to work, and tests out locally.

**Review by mlsamuelson — APPROVED** [review]

**Pull request merged**
